name: Lint and test vue package

on:
    push:
        paths:
            - 'packages/vue/**'

jobs:
    lint:
        name: Lint and test Butlerov Vue package
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: "24"
                  cache: npm
            - name: Install dependencies
              run: npm ci

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps

            - name: Build Vue package
              run: npm run build --workspace=packages/vue

            - name: Run Playwright tests
              run: npm run test --workspace=packages/vue
