name: Lint and test vue package

on:
    push:
        paths:
            - 'packages/vue/**'

jobs:
    lint:
        name: Lint and test Butlerov Vue package
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            -
                uses: actions/setup-node@v4
                with:
                    node-version: 20
                    cache: npm
            - run: npm ci
            - run: npm --workspace=packages/vue run lint
            - run: npm --workspace=packages/vue run test
